version: '3.8'

services:
  api:
    build: ./api_service
    env_file:
      - ./api_service/.env.api.example
    command: ["sh", "-c", "echo $SERVER_PORT && exec your_api_command"]
    environment:
      - SERVER_PORT=8081
      - SERVER_READ_TIME=${SERVER_READ_TIME}
      - SERVER_WRITE_TIME=${SERVER_WRITE_TIME}
      - URL_AUTH=http://auth:8080/api/v1
      - URL_WAREHOUSE=${URL_WAREHOUSE}
      - AUTH_AT_DURATION=${AUTH_AT_DURATION}
      - AUTH_RF_DURATION=${AUTH_RF_DURATION}
      - AUTH_PRIVATE_KEY_PATH=${AUTH_PRIVATE_KEY_PATH}
      - AUTH_PUBLIC_KEY_PATH=${AUTH_PUBLIC_KEY_PATH}
    ports:
      - 8081:8081
    depends_on:
      - auth
  auth:
    build: ./auth_service
    env_file:
      - ./auth_service/.env.auth.example
    environment:
      - PG_USERNAME=${PG_USERNAME}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=5432
      - PG_HOST=auth_db
      - PG_POOL_MAX=${PG_POOL_MAX}
      - PG_DBNAME=${PG_DBNAME}
      - PG_TIMEOUT=${PG_TIMEOUT}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_READ_TIME=${SERVER_READ_TIME}
      - SERVER_WRITE_TIME=${SERVER_WRITE_TIME}
      - AUTH_AT_DURATION=${AUTH_AT_DURATION}
      - AUTH_RF_DURATION=${AUTH_RF_DURATION}
      - AUTH_PRIVATE_KEY_PATH=${AUTH_PRIVATE_KEY_PATH}
      - AUTH_PUBLIC_KEY_PATH=${AUTH_PUBLIC_KEY_PATH}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - auth_db

  auth_db:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - .data/pg:/var/lib/postgresql/data
        
volumes:
  db:
    driver: local